Fix -spec(_).s as much as possible
miniclip/erl_cbor pull request #10
Opened 2021-08-04 14:36 UTC by paulo-ferraz-oliveira

2021-08-04 14:36 UTC, paulo-ferraz-oliveira commented
I'll self-review now.

2021-08-04 14:52 UTC, paulo-ferraz-oliveira commented on rebar.config
> +    warn_missing_spec,
It was already the case, it just wasn't un-commented.

2021-08-04 14:56 UTC, paulo-ferraz-oliveira commented on src/erl_cbor_decoding.erl
> -maybe_interpret_value(_Decoder, {_Type, {error, _Value} = Tag}) ->
Naming, right?

2021-08-04 14:56 UTC, paulo-ferraz-oliveira commented on src/erl_cbor_decoding.erl
> --spec interpret_value(decoder(), erl_cbor:value() | erl_cbor:value()) ->
Yes, thank you!

2021-08-04 14:58 UTC, paulo-ferraz-oliveira commented
Most of the changes are internal. I believe no interface has been broken.

2021-08-04 15:42 UTC, paulo-ferraz-oliveira commented
Moving to draft to test with a consumer app.

2021-08-09 13:00 UTC, g-andrade requested changes

2021-08-09 13:00 UTC, g-andrade commented on src/erl_cbor_base64.erl
> +-spec decode(binary()) -> {ok, binary()} | {error, {invalid_data, binary()}}.
^ There's also [`{error, {invalid_base64_digit, byte()}}`](https://github.com/miniclip/erl_cbor/blob/8683263e7df4258e063e48ed0e99e31886dd0834/src/erl_cbor_base64.erl#L75)

2021-08-09 13:00 UTC, g-andrade commented on src/erl_cbor_base64url.erl
> +-spec decode(binary()) -> {ok, binary()} | {error, badarith}.
^ Where did `badarith` come from? (I can't find it as an implicitly possible throw among the bitwise ops in this module.)

As far as I can tell, the only errors thrown are the same as (or analogous to) the ones in `erl_cbor_base64`.

2021-08-09 13:00 UTC, g-andrade commented on src/erl_cbor_decoding.erl
> +                               {invalid_base64url_data, badarith} |
^ (Reminder) These two are subject to change, depending on how comments on `erl_cbor_base64` and `erl_cbor_base64url` are handled.

2021-08-09 13:00 UTC, g-andrade commented on src/erl_cbor_decoding.erl
> -maybe_interpret_value(_Decoder, {_Type, {error, _Value} = Tag}) ->
🥴

2021-08-09 13:00 UTC, g-andrade commented on src/erl_cbor_decoding.erl
> --spec interpret_value(decoder(), erl_cbor:value() | erl_cbor:value()) ->
It's not _technically_ incorrect 🤔.

2021-08-09 13:00 UTC, g-andrade commented on src/erl_cbor_decoding.erl
> +-spec interpret_utf8_string({erl_cbor:type(), binary()}) ->
^ Should `erl_cbor:type()` be `erl_cbor:tag()`, here?

2021-08-09 13:00 UTC, g-andrade commented on src/erl_cbor_decoding.erl
> +-spec interpret_epoch_based_datetime({erl_cbor:type(), number()}) ->
^ Should `erl_cbor:type()` be `erl_cbor:tag()`, here?

(...and so on in analogous changes throughout `interpret_*` functions in this module.)

2021-08-09 13:00 UTC, g-andrade commented on src/erl_cbor_decoding.erl
> +-spec interpret_utf8_string({erl_cbor:type(), binary()}) ->
I can see that it shouldn't.

2021-08-09 13:00 UTC, g-andrade commented on src/erl_cbor_decoding.erl
> +-spec interpret_epoch_based_datetime({erl_cbor:type(), number()}) ->
I can see that it shouldn't. Confusing...

2021-08-09 13:00 UTC, g-andrade commented on src/erl_cbor_encoding.erl
> +-spec encode_integer(integer()) -> nonempty_binary() | nonempty_list(<<_:8>> | unicode:chardata()).
^ `unicode:chardata()` shouldn't apply, here (I'm guessing some dependent is saying it returns it but it shouldn't.)

At most, `iodata()`.

2021-08-09 13:00 UTC, g-andrade commented on src/erl_cbor_encoding.erl
> +-spec encode_float(float()) -> <<_:72>>.
Internal specs. Fun stuff. 🙂

2021-08-09 13:00 UTC, g-andrade commented on src/erl_cbor_encoding.erl
> +-spec encode_binary(binary()) -> unicode:chardata().
Whence cometh `unicode:chardata()`?

2021-08-09 13:00 UTC, g-andrade commented on src/erl_cbor_util.erl
> +-spec hex_string_to_binary(unicode:chardata()) -> binary().
^ This function's input doesn't look restricted to UTF-8 binaries; it doesn't handle character lists, either. Therefore its input is `binary()` (necessarily.)

2021-08-09 13:00 UTC, g-andrade commented on src/erl_cbor_util.erl
> +-spec hex_string_to_binary(unicode:chardata()) -> binary().
(For context: `unicode:chardata()` is defined as [either a `:charlist()` _or_ a `:unicode_binary()`](http://erlang.org/doc/man/unicode.html#type-chardata).)

2021-08-09 23:42 UTC, paulo-ferraz-oliveira commented on src/erl_cbor_base64.erl
> +-spec decode(binary()) -> {ok, binary()} | {error, {invalid_data, binary()}}.
Yup: 4f6f96f

2021-08-09 23:43 UTC, paulo-ferraz-oliveira commented on src/erl_cbor_decoding.erl
> +                               {invalid_base64url_data, badarith} |
ea6acf9

2021-08-09 23:47 UTC, paulo-ferraz-oliveira commented on src/erl_cbor_base64url.erl
> +-spec decode(binary()) -> {ok, binary()} | {error, badarith}.
Hm... it comes from "that's what reviews are for" 😄 I can't actually remember... but 8556782

2021-08-09 23:47 UTC, paulo-ferraz-oliveira commented on src/erl_cbor_base64.erl
> +-spec decode(binary()) -> {ok, binary()} | {error, {invalid_data, binary()}}.
Yup: 8556782

2021-08-09 23:52 UTC, paulo-ferraz-oliveira commented on src/erl_cbor_encoding.erl
> +-spec encode_integer(integer()) -> nonempty_binary() | nonempty_list(<<_:8>> | unicode:chardata()).
985537d

2021-08-09 23:53 UTC, paulo-ferraz-oliveira commented on src/erl_cbor_encoding.erl
> +-spec encode_float(float()) -> <<_:72>>.
I though about deleting this (it would make both you and me happy, in this specific case). I like internal `-spec(_).` especially when they have value, which is not exactly the case.

2021-08-09 23:55 UTC, paulo-ferraz-oliveira commented on src/erl_cbor_encoding.erl
> +-spec encode_binary(binary()) -> unicode:chardata().
My laptop was hacked 🤷‍♂️

2021-08-09 23:55 UTC, paulo-ferraz-oliveira commented on src/erl_cbor_encoding.erl
> +-spec encode_binary(binary()) -> unicode:chardata().
b108452

2021-08-09 23:57 UTC, paulo-ferraz-oliveira commented on src/erl_cbor_util.erl
> +-spec hex_string_to_binary(unicode:chardata()) -> binary().
"hacked"...: 429dc03

2021-08-10 13:15 UTC, g-andrade commented on src/erl_cbor_base64.erl
> +-spec decode(binary()) -> {ok, binary()} | {error, {invalid_data, binary()}}.
👍

2021-08-10 13:16 UTC, g-andrade commented on src/erl_cbor_encoding.erl
> +-spec encode_binary(binary()) -> unicode:chardata().
> My laptop was hacked

😄

2021-08-10 13:17 UTC, g-andrade approved these changes

2021-08-10 13:18 UTC, merged