Introduce rebar3_hank
miniclip/erl_cbor pull request #8
Opened 2021-06-21 21:06 UTC by paulo-ferraz-oliveira

2021-06-22 16:00 UTC, g-andrade commented
Missing a CHANGELOG update

2021-06-22 16:01 UTC, g-andrade approved these changes

2021-06-22 16:03 UTC, g-andrade commented
(I can't revert my approval)

2021-06-22 17:57 UTC, g-andrade approved these changes

2021-06-22 18:01 UTC, g-andrade commented on CHANGELOG.md
> +- CI container approach to `setup-beam` with cache [Paulo Oliveira]
^ Please place these in a new `[Unreleased]` section and re-title the existing one to `2.0.0`, dated June 16th - the changes in question have been released. 

My brain must have not been fully functional on that day...

2021-06-22 18:07 UTC, g-andrade commented on CHANGELOG.md
> +- CI container approach to `setup-beam` with cache [Paulo Oliveira]
Never mind - I've fixed in in #9 . You'll just need to rebase.

2021-06-22 18:08 UTC, g-andrade requested changes
Please rebase in order to add the new CHANGELOG entries in the right place, following #9 (sorry about that)

2021-06-22 18:10 UTC, paulo-ferraz-oliveira commented
Shiiiiieeeeeeeet.

2021-06-22 18:12 UTC, g-andrade commented
![image](https://user-images.githubusercontent.com/7349502/122977880-cc843d00-d38d-11eb-9d3b-dd982c3e330a.jpg)

2021-06-22 18:14 UTC, g-andrade commented on CHANGELOG.md
> +- CI container approach to `setup-beam` with cache [Paulo Oliveira]
(I see you rebased, but the new entries are still in the wrong place)

2021-06-22 18:15 UTC, g-andrade commented on CHANGELOG.md
> +- CI container approach to `setup-beam` with cache [Paulo Oliveira]
[I guess I should have been more explicit about "just need to rebase"]

2021-06-22 18:17 UTC, paulo-ferraz-oliveira commented on CHANGELOG.md
> +- CI container approach to `setup-beam` with cache [Paulo Oliveira]
There's this thing here: Allow edits and access to secrets by maintainers. I left it checked.

2021-06-22 18:32 UTC, g-andrade commented on CHANGELOG.md
> +- CI container approach to `setup-beam` with cache [Paulo Oliveira]
Ahh, I considered it but thought you didn't like to use it. I'll fix the issue then

2021-06-22 18:37 UTC, g-andrade commented on CHANGELOG.md
> +- CI container approach to `setup-beam` with cache [Paulo Oliveira]
276fd63

2021-06-22 18:37 UTC, g-andrade approved these changes

2021-06-22 18:37 UTC, merged

2021-06-23 08:59 UTC, paulo-ferraz-oliveira commented on CHANGELOG.md
> +- CI container approach to `setup-beam` with cache [Paulo Oliveira]
You are half right; I don't like to use it when it's code in a major way. If it's just a small tweak, you can either propose a suggestion or change yourself, but I don't expect people to know this is how I think about the subject. 😄